%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c jpyy.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  newvision.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  kankan70.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  tiantian.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  xb6v.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  mp4movie.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  jianpian.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  alipansou.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  huya.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  star.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  nivod.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  aiyingshi.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  sp360.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  mxanime.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  cntv.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  douban.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  pan_search.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  bilibili.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  changzhang.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  wogg.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  nangua.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  aliyunpanshare.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  dubo.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  haiwaikan.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  dygangs.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  cilixiong.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  lovemovie.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  gitcafe.js
%~dp0\TVSpiderJS\qjsc_open.exe -I %~dp0\TVSpiderJS\dist\ -O %cd%\json\js -m -c  kuaikan.js
